config/routes.rb
Rails.application.routes.draw do
  resources :microposts
  resources :users
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  validates :content, length: {maximum: 140},
                      presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts
  validates :name, length: {maximum: 50},
                    presence: true
  validates :email, length: {maximum: 50},
                    presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def hello
    render html: "hey!"
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: %i[ show edit update destroy ]

  # GET /microposts or /microposts.json
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1 or /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts or /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: "Micropost was successfully created." }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1 or /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: "Micropost was successfully updated." }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1 or /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: "Micropost was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def micropost_params
      params.require(:micropost).permit(:content, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/microposts/_form.html.erb
<%= form_with(model: micropost) do |form| %>
  <% if micropost.errors.any? %>
    <div class="pl-6 pt-6">
      <div class="py-2 px-4 rounded-lg max-w-sm text-xl text-white bg-red-500">
        <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

        <ul>
          <% micropost.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="pl-6 pt-6">
    <%= form.label :content, class: "text-xl font-semibold" %>
    <%= form.text_area :content, placeholder: "content", class: "rounded text-xl shadow-md border border-transparent focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent" %>
  </div>

  <div class="pl-6 pt-6">
    <%= form.label :user_id, class: "text-xl font-semibold" %>
    <%= form.number_field :user_id, placeholder: "user id", class: "rounded text-xl shadow-md border border-transparent focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent" %>
  </div>

  <div class="pl-6 pt-6">
    <%= form.submit class: "btn-blue" %>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<h1 class="text-xl font-semibold text-blue-500 underline pl-6 pt-6">
  Editing Micropost
</h1>

<%= render 'form', micropost: @micropost %>

<div class="pl-6 pt-6">
  <%= link_to 'Show', @micropost, class: "btn-blue" %>
  <%= link_to 'Back', microposts_path, class: "btn-blue" %>
</div>

app/views/microposts/index.html.erb
<p class="text-xl text-green-700 pl-6 pt-6"><%= notice %></p>

<h1 class="text-xl font-semibold text-blue-500 underline pl-6 pt-6">
  Microposts
</h1>

<div class="pl-6 pr-6 pt-6">
  <table class ="table-fixed border-collapse">
    <thead>
      <tr>
        <th class="w-56 border border-blue-500">Content</th>
        <th class="w-56 border border-blue-500">User</th>
        <th class="w-56 border border-blue-500" colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @microposts.each do |micropost| %>
        <tr>
          <td class="w-56 border border-blue-500"><%= micropost.content %></td>
          <td class="w-56 border border-blue-500"><%= micropost.user_id %></td>
          <td class="w-56 border border-blue-500" colspan="3">
            <div class="pl-1">
              <%= link_to 'Show', micropost, class: "btn-mini" %>
              <%= link_to 'Edit', edit_micropost_path(micropost), class: "btn-mini" %>
              <%= link_to 'Destroy', micropost, class: "btn-mini", method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

<div class="pl-6 pt-6">
  <%= link_to 'New Micropost', new_micropost_path, class: "btn-blue" %>
</div>

app/views/microposts/new.html.erb
<h1 class="text-xl font-semibold text-blue-500 underline pl-6 pt-6">
  New Micropost
</h1>

<%= render 'form', micropost: @micropost %>

<div class="pl-6 pt-6">
  <%= link_to 'Back', microposts_path, class: "btn-blue"%>
</div>

app/views/microposts/show.html.erb
<p class="text-xl text-green-700 pl-6 pt-6"><%= notice %></p>

<div class="pl-6 pt-6">
  <p>
    <strong class="text-xl font-semibold">
      Content:
    </strong>
    <%= @micropost.content %>
  </p>

  <p>
    <strong class="text-xl font-semibold">
      User:
    </strong>
    <%= @micropost.user_id %>
  </p>
</div>

<div class="pl-6 pt-6">
  <%= link_to 'Edit', edit_micropost_path(@micropost), class: "btn-blue" %>
  <%= link_to 'Back', microposts_path, class: "btn-blue" %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div class="pl-6 pt-6">
      <div class="py-2 px-4 rounded-lg max-w-sm text-xl text-white bg-red-500">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
          <% user.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="pl-6 pt-6">
    <%= form.label :name, class: "text-xl font-semibold" %>
    <%= form.text_field :name, placeholder: "name", class: "rounded text-xl shadow-md border border-transparent focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent" %>
  </div>

  <div class="pl-6 pt-6">
    <%= form.label :email, class: "text-xl font-semibold" %>
    <%= form.text_field :email, placeholder: "email", class: "rounded text-xl shadow-md border border-transparent focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent" %>
  </div>

  <div class="pl-6 pt-6">
    <%= form.submit class: "btn-blue" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1 class="text-xl font-semibold text-blue-500 underline pl-6 pt-6">
  Editing User
</h1>

<%= render 'form', user: @user %>

<div class="pl-6 pt-6">
  <%= link_to 'Show', @user, class: "btn-blue" %>
  <%= link_to 'Back', users_path, class: "btn-blue" %>
</div>

app/views/users/index.html.erb
<p class="text-xl text-green-700 pl-6 pt-6"><%= notice %></p>

<h1 class="text-xl font-semibold text-blue-500 underline pl-6 pt-6">
  Users
</h1>

<div class="pl-6 pr-6 pt-6">
  <table class ="table-fixed border-collapse">
    <thead>
      <tr>
        <th class="w-56 border border-blue-500">Name</th>
        <th class="w-56 border border-blue-500">Email</th>
        <th class="w-56 border border-blue-500" colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td class="w-56 border border-blue-500"><%= user.name %></td>
          <td class="w-56 border border-blue-500"><%= user.email %></td>
          <td class="w-56 border border-blue-500" colspan="3">
            <div class="pl-1">
              <%= link_to 'Show', user, class: "btn-mini" %>
              <%= link_to 'Edit', edit_user_path(user), class: "btn-mini" %>
              <%= link_to 'Destroy', user, class: "btn-mini", method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<div class="pl-6 pt-6">
  <%= link_to 'New User', new_user_path, class: "btn-blue"%>
</div>

app/views/users/new.html.erb
<h1 class="text-xl font-semibold text-blue-500 underline pl-6 pt-6">
  New User
</h1>

<%= render 'form', user: @user %>

<div class="pl-6 pt-6">
  <%= link_to 'Back', users_path, class: "btn-blue"%>
</div>

app/views/users/show.html.erb
<p class="text-xl text-green-700 pl-6 pt-6"><%= notice %></p>

<div class="pl-6 pt-6">
  <p>
    <strong class="text-xl font-semibold">
      Name:
    </strong>
    <%= @user.name %>
  </p>

  <p>
    <strong class="text-xl font-semibold">
      Email:
    </strong>
    <%= @user.email %>
  </p>

  <p>
    <strong class="text-xl font-semibold">
    First Micropost:
    </strong>
    <%= if @user.microposts.present?
          @user.microposts.first.content
        end %>
  </p>
</div>

<div class="pl-6 pt-6">
  <%= link_to 'Edit', edit_user_path(@user), class: "btn-blue" %> 
  <%= link_to 'Back', users_path, class: "btn-blue" %>
</div>